version: '3.8'

services:
  backend:
    build:
      context: ./api/api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}

  frontend:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend