version: '3.8'

services:
  backend:
    build:
      context: ./api/api
    ports:
      - "8080:8080"
    env_file: ./.env

  frontend:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend